name: C/C++ CI

on:
  push:
    paths: 
      - linux
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download
      run: sudo apt-get install gcc-8
      run: wget https://github.com/jaeckiee/linux/archive/$(git rev-parse @:./linux).zip -O linux.zip
    - name: Unzip
      run: unzip linux.zip
    - name: config and build
      run: ./build-linux.sh linux-$(git rev-parse @:./linux) tinyconfig
